#configure tasks file in ansible
---
- name: Update package cache and setup server
  hosts: localhost
  become: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install common package
      apt:
        name: "{{ install }}"
        state: present

    - name: Create app user
      user:
        name: "{{ db_user }}"
        state: present
